version: '3.7'

services:
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - /home/sanjiv/workspace/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

  web:
    build: .
    image: house:latest
    container_name: house_app
    restart: always
    env_file:
      - ./.environment
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /home/sanjiv/workspace/backup:/backup
    ports:
      - "8081:8000"
    depends_on: 
      - mongodb
    links:
      - mongodb
