# Generated by Django 2.2.4 on 2020-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('origin', models.CharField(default='INDIA', max_length=16)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('pq', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
